swsnu/swppfall2022-team8

frontend/src/App.tsx, frontend/src/store/index.ts, frontend/src/store/slices/book/book.ts, frontend/src/store/slices/borrow/borrow.ts, frontend/src/store/slices/lend/lend.ts, frontend/src/store/slices/user/user.ts
navigate root path to main page,
navigate invalid path to 404 page
(new) ChattingPage path: /chatting -> /chat
=> Create Redux state & modify App.tsx

frontend/src/store/slices/book/book.ts, frontend/src/store/slices/lend/lend.ts
1. Lend.additional의 타입을 string으로 바꿈
2. search params의 tag 프로퍼티의 타입을 string[]으로 바꿈
=> redux minor fix

frontend/src/components/BookListEntity/BookListEntity.tsx, frontend/src/containers/BookListPage/BookListPage.tsx, frontend/src/containers/BookRequestPage/BookRequestPage.tsx, frontend/src/containers/MainPage/MainPage.tsx
=> MainPage BookListPage BookRequestPage

backend/bookVillage/book/views/borrow_info_view.py
=> lend_id_bug_fix

frontend/src/App.css, frontend/src/components/LogoButton/LogoButton.css, frontend/src/components/LogoButton/LogoButton.tsx, frontend/src/components/SearchBar/SearchBar.tsx, frontend/src/containers/BookDetailPage/BookDetailPage.tsx, frontend/src/index.tsx
=> logo and search bar

frontend/package.json, frontend/src/App.tsx, frontend/src/components/SearchBar/SearchBar.tsx, frontend/src/containers/BookListPage/BookListPage.tsx, frontend/src/containers/MainPage/MainPage.tsx, frontend/src/store/slices/book/book.ts, frontend/src/store/slices/lend/lend.ts, frontend/yarn.lock
1. SearchBar component에서 tag 및 author 기반 검색 기능 추가
2. BookListPage의 라우팅을 `/search/:key`에서 `/search`로 변경 (query string은 useLocation Hook으로 받을 수 있음)
3. 더 나은 query string 기능을 위한 `qs` 모듈을 package.json에 추가
4. 가독성을 위해 frontend에서 search parameter의 순서를 title, author, tag 순으로 고정
=> add tag/author-based search feature

frontend/src/containers/BookRegisterPage/BookRegisterPage.css, frontend/src/containers/BookRegisterPage/BookRegisterPage.tsx
바꾼건 additional info 입력칸이 input이면 개행이나 길어질 때 대비가 안돼서 textarea로 바꿨음
그리고 label 같은거 약간 대충 했는데 나중에 test 할 때는 id로 하거나 아님 문제 생기면 수정하거나 해야 할듯?
=> register page 다 만듦

frontend/src/components/LogoButton/LogoButton.css, frontend/src/containers/BookDetailPage/BookDetailPage.css, frontend/src/containers/BookDetailPage/BookDetailPage.tsx, frontend/src/containers/BookEditPage/BookEditPage.css, frontend/src/containers/BookEditPage/BookEditPage.tsx, frontend/src/containers/BookRegisterPage/BookRegisterPage.css, frontend/src/containers/BookRegisterPage/BookRegisterPage.tsx
detail page 완성
register page 아주아주 약간 수정
=> Sb css detailpage

frontend/src/components/BookListEntity/BookListEntity.test.tsx, frontend/src/components/BookListEntity/BookListEntity.tsx, frontend/src/components/ChattingButton/ChattingButton.test.tsx, frontend/src/components/ChattingRigntMenu/ChattingRightMenu.test.tsx, frontend/src/components/ChattingRoom/ChattingRoom.test.tsx, frontend/src/components/ChattingRoomList/ChattingRoomList.test.tsx, frontend/src/components/LogoButton/LogoButton.test.tsx, frontend/src/components/LogoutButton/LogoutButton.test.tsx, frontend/src/components/NavBar/NavBar.test.tsx, frontend/src/components/Recommend/Recommend.test.tsx, frontend/src/components/RecommendEntity/RecommendEntity.test.tsx, frontend/src/components/RegisterButton/RegisterButton.test.tsx, frontend/src/components/SearchBar/SearchBar.test.tsx, frontend/src/components/UserStatusButton/UserStatusButton.test.tsx
frontend/src/components폴더의 test coverage 100% 완료
=> Frontentd components test

frontend/src/containers/BookDetailPage/BookDetailPage.css, frontend/src/containers/LoginPage/LoginPage.css, frontend/src/containers/LoginPage/LoginPage.tsx, frontend/src/containers/SignupPage/SignupPage.css, frontend/src/containers/SignupPage/SignupPage.tsx, frontend/src/containers/UserStatusPage/UserStatusPage.css, frontend/src/containers/UserStatusPage/UserStatusPage.tsx
signin page 간단하게 만듦 + 그리고 user status page 약간 만짐
=> Sb css signin

frontend/src/store/slices/book/book.test.ts, frontend/src/store/slices/book/book.ts, frontend/src/store/slices/borrow/borrow.test.ts, frontend/src/store/slices/lend/lend.test.ts, frontend/src/store/slices/lend/lend.ts, frontend/src/store/slices/room/room.test.ts, frontend/src/store/slices/user/user.test.ts, frontend/src/store/slices/user/user.ts
특이사항)
Slices 파일들에서 일부 fetch 함수의 경우 return response.data ?? null 로 되어있던데 null 필요없는 것 같아서 지움
Uncovered line은 없는데 사진처럼 일부 functions가 100퍼가 안뜸
=> Frontend Slices Test

frontend/src/components/SearchBar/SearchBar.test.tsx, frontend/src/components/SearchBar/SearchBar.tsx
1. search bar UX 개선
2. 수정사항에 대한 테스팅 작성
=> fix search bar

backend/runserver.sh
backend폴더에서 `source runserver.sh` 만 입력하면 venv activate부터 redis, celery 실행이 한번에?!
정말 편하다아아아앗~~!!!
=> Runserver macro 추가

frontend/src/containers/BookDetailPage/BookDetailPage.tsx, frontend/src/containers/BookEditPage/BookEditPage.test.tsx, frontend/src/containers/BookEditPage/BookEditPage.tsx, frontend/src/containers/BookRegisterPage/BookRegisterPage.test.tsx, frontend/src/containers/BookRegisterPage/BookRegisterPage.tsx, frontend/src/containers/ChattingPage/ChattingPage.test.tsx, frontend/src/store/slices/lend/lend.test.ts, frontend/src/store/slices/lend/lend.ts
일단 Register page에서 post하는 것까지 만듬
lend image는 최대 3개까지 가능
=> lend image POST implemented

frontend/src/containers/ChattingPage/ChattingPage.test.tsx
=> ChattingPage test fix

frontend/src/components/PageButton/PageButton.test.tsx, frontend/src/components/PageButton/PageButton.tsx, frontend/src/containers/BookDetailPage/BookDetailPage.test.tsx, frontend/src/containers/BookDetailPage/BookDetailPage.tsx, frontend/src/containers/BookListPage/BookListPage.test.tsx, frontend/src/containers/BookListPage/BookListPage.tsx, frontend/src/containers/UserStatusPage/UserStatusPage.test.tsx, frontend/src/containers/UserStatusPage/UserStatusPage.tsx
1. Pagination Button 컴포넌트를 만들고 이를 BookListPage, UserStatusPage에 적용
2. BookDetailPage에서 보이는 tag에 대해 유사(?) pagination 적용 (이건 보고 평가 좀)
3. 위 수정사항에 대해 테스팅 작성
=> pagination in frontend

frontend/src/components/SearchBar/SearchBar.test.tsx, frontend/src/components/SearchBar/SearchBar.tsx, frontend/src/containers/UserStatusPage/UserStatusPage.tsx, frontend/src/store/slices/book/book.ts, frontend/src/utils/useInterval.tsx
1. frontend/utils 폴더에 useInterval 커스텀 hook 추가
- 사용법: setInterval과 같음
- 주의점: useEffect 안에다 넣지 말것. useEffect 쓰는 위치와 같은 위치에서 사용해야 함
2. SearchBar / UserStatusPage에 tag 자동완성 추가
- 테스팅은 포기함
=> add tag autocomplete in frontend

frontend/src/components/SearchBar/SearchBar.tsx, frontend/src/containers/BookRegisterPage/BookRegisterPage.test.tsx, frontend/src/containers/BookRegisterPage/BookRegisterPage.tsx, frontend/src/containers/UserStatusPage/UserStatusPage.tsx
테스트 아직 수정 안함
RegisterPage에서 title로 책 검색 가능하도록 함
UserStatus, SearchBar에서 자동완성 리스트 클릭하면 onBlur 실행되는 문제 해결
=> autocomplete

backend/bookVillage/user/tasks.py
=> recommend 알고리즘 개선

frontend/src/components/Recommend/Recommend.test.tsx, frontend/src/components/Recommend/Recommend.tsx
0.5초마다 is_outdated = False로 변경될 때 까지 계속 fetchRecommend 시행함
Refresh버튼 삭제함
=> Recommend 0.5초마다

frontend/src/components/SearchBar/SearchBar.test.tsx, frontend/src/containers/BookDetailPage/BookDetailPage.test.tsx, frontend/src/containers/BookDetailPage/BookDetailPage.tsx, frontend/src/containers/BookRequestPage/BookRequestPage.test.tsx, frontend/src/containers/ChattingPage/ChattingPage.tsx, frontend/src/containers/LoginPage/LoginPage.test.tsx, frontend/src/containers/LoginPage/LoginPage.tsx, frontend/src/containers/MainPage/MainPage.test.tsx, frontend/src/containers/SignupPage/SignupPage.test.tsx, frontend/src/containers/UserStatusPage/UserStatusPage.test.tsx
1. 테스팅 작성
2. ChattingRoomList가 비어 있을 때 채팅방은 request를 받거나 하면 생긴다고 설명하는 문구 추가
=> 12.09 testing

frontend/src/components/BookListEntity/BookListEntity.css, frontend/src/components/BookListEntity/BookListEntity.tsx, frontend/src/components/Footer/Footer.tsx, frontend/src/components/LogoButton/LogoButton.css, frontend/src/components/NavBar/NavBar.css, frontend/src/components/NavBar/NavBar.tsx, frontend/src/components/SearchBar/SearchBar.css, frontend/src/containers/BookDetailPage/BookDetailPage.css, frontend/src/containers/BookEditPage/BookEditPage.css, frontend/src/containers/BookEditPage/BookEditPage.tsx, frontend/src/containers/BookListPage/BookListPage.css, frontend/src/containers/BookRegisterPage/BookRegisterPage.css, frontend/src/containers/BookRegisterPage/BookRegisterPage.tsx, frontend/src/containers/BookRequestPage/BookRequestPage.css, frontend/src/containers/LoginPage/LoginPage.css, frontend/src/containers/MainPage/MainPage.css, frontend/src/containers/MainPage/MainPage.tsx
1. 웹페이지 디자인 수정 (이제 width 400px까지 줄여도 나름 괜찮게 보임)
2. offcanvas 글자 삭제, offcanvas에서 버튼을 누르면 offcanvas가 접히도록 수정
3. BookRegisterPage, BookEditPage에서 lend image carousel 높이 제한
4. BookRegisterPage, BookEditPage에서 lend image 업로드 시 carousel이 그 사진을 보여주도록 수정
5. BookEditPage에서 lend image를 전부 삭제하고 confirm하려고 하는 경우 modal을 띄우도록 수정
=> 12.11 improve design
